menus:
  - section: orders
    text: "订单"
    path: "/orders"
    children:
      - {text: "面单上传", href: "/orders/label-upload"}
  - section: logistics
    text: "物流"
    path: "/logistics"
    children:
      - {text: "物流渠道", href: "/logistics/channels"}
