# 一级/二级/三级导航注册（示例）
main:
  - key: orders
    text: 订单
    sub:
      - { text: 预报, href: /orders/prealert }
      - { text: 订单列表, href: /orders/list }
      - { text: 面单上传, href: /orders/label-upload }
      - { text: 订单轨迹, href: /orders/track }
      - { text: 订单规则, href: /orders/rules }

  - key: products
    text: 商品
    sub:
      - { text: 商品列表, href: /products/list }
      - { text: 定制规则, href: /products/custom-rules }

  - key: logistics
    text: 物流
    sub:
      - { text: 物流规则, href: /logistics/rules }
      - { text: 物流渠道, href: /logistics/channels }
      - { text: 地址管理, href: /logistics/address }

  - key: settings
    text: 设置
    sub:
      - { text: 仓库设置, href: /settings/warehouse }
      - { text: 服务商授权, href: /settings/provider-auth }
      - { text: 店铺授权, href: /settings/shop-auth }
      - { text: 客户端管理, href: /settings/client }
      - { text: 系统设置, href: /settings/system }
