# label_upload.outbound.yaml
# 出站接口（供前端/第三方调用）
get_list:
  method: GET
  path: /api/label-upload/list
import_label:
  method: POST
  path: /api/label-upload/import-label
import_map:
  method: POST
  path: /api/label-upload/import-map
batch_void:
  method: POST
  path: /api/label-upload/batch-void
batch_delete:
  method: POST
  path: /api/label-upload/batch-delete
file_preview:
  method: GET
  path: /api/label-upload/file/{id}
