# deploy/docker-compose.yml
# 统一 Docker 编排（profiles: web, backend, postgres, editor）
# - 后端改用 DATABASE_URL（asyncpg），与代码一致；Jinja 自动重载开关保留

services:
  db:
    image: postgres:15
    container_name: minipost_db
    environment:
      POSTGRES_USER: minipost
      POSTGRES_PASSWORD: minipost
      POSTGRES_DB: minipost
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minipost"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    profiles: ["postgres"]

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: minipost-backend
    container_name: minipost_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://minipost:minipost@db:5432/minipost   # ← 修正点
      APP_ENV: production
      APP_PORT: 8000
      JINJA_AUTO_RELOAD: "1"
    expose:
      - "8000"
    # 如果后端确实要从容器内文件系统读模板/静态，可按实际路径打开挂载：
    # volumes:
    #   - ../backend/templates:/app/app/templates:rw
    #   - ../backend/static:/app/app/static:rw
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/docs', timeout=2)"]
      interval: 5s
      timeout: 3s
      retries: 40
    restart: unless-stopped
    profiles: ["backend"]

  web:
    build:
      context: ../frontend
    image: minipost-web
    container_name: minipost_web
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8000:80"
    restart: unless-stopped
    profiles: ["web"]

  editor:
    build:
      context: ../editor
      dockerfile: Dockerfile
    image: minipost-editor
    container_name: minipost_editor
    environment:
      ROOT_DIR: /workspace
      EDITOR_USER: ${EDITOR_USER:-daddy}
      EDITOR_PASS: ${EDITOR_PASS:-20240314AaA#}
      EDITOR_PORT: ${EDITOR_PORT:-6006}
    ports:
      - "${EDITOR_PORT:-6006}:6006"
    volumes:
      - ..:/workspace:rw
    # 如需 <1024 端口可加：
    # cap_add: [ "NET_BIND_SERVICE" ]
    restart: unless-stopped
    profiles: ["editor"]

volumes:
  db_data:
