l1:
  - { key: settings, text: "设置", href: "/settings", order: 90 }
l2:
  "/settings":
    - { text: "账号与权限", href: "/settings/rbac", order: 10, require_all: ["rbac.manage"], visible_when_denied: true }
l3: {}
