roles:
  - code: admin
    name: 管理员
    perms:
      - system.admin
      - shell.view
      - orders.view
      - products.view
      - logistics.view
      - settings.view
      - users.manage
  - code: ops
    name: 运营
    perms:
      - shell.view
      - orders.view
      - products.view
      - logistics.view
  - code: viewer
    name: 只读
    perms:
      - shell.view
