roles:
  - role_code: admin
    role_name: 超级管理员
    permission_keys:
      - superuser
      - nav.rebuild
      - core.users.view
      - core.roles.view
      - core.roles.manage
  - role_code: ops
    role_name: 运营
    permission_keys:
      - core.users.view
      - core.roles.view
      - nav.view
  - role_code: viewer
    role_name: 只读
    permission_keys:
      - nav.view
