version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.deploy.env
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASS}@postgres:${DB_PORT}/${DB_NAME}
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
      - ../modules/nav-shell/cache:/app/modules/nav-shell/cache
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30

  postgres:
    image: postgres:16-alpine
    env_file: ../.deploy.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ../data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 60
