version: "3.9"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ../docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../logs/nginx:/var/log/nginx
      - ../data/cert:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      web:
        condition: service_healthy
