services:
  nginx:
    image: nginx:1.25-alpine
    container_name: minipost_nginx
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../data/certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
