version: "3.9"
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: minipost-nginx
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${DATA_ROOT:-/opt/minipost/data}/certs:/certs:ro
    restart: unless-stopped
