l1:
  - key: dashboard
    text: 仪表盘
    href: /dashboard
    order: 10
  - key: rbac
    text: 权限
    href: /rbac
    order: 90
    require_any: ["core.users.view","core.roles.view"]
  - key: settings
    text: 系统设置
    href: /settings
    order: 95
    require_all: ["settings.view"]
    visible_when_denied: true

l2:
  "/dashboard":
    - key: overview
      text: 总览
      href: /dashboard/overview
      order: 10
  "/rbac":
    - key: users
      text: 用户
      href: /rbac/users
      order: 10
      require_all: ["core.users.view"]
    - key: roles
      text: 角色
      href: /rbac/roles
      order: 20
      require_all: ["core.roles.view"]
  "/settings":
    - key: system
      text: 系统
      href: /settings/system
      order: 10

l3: {}
