# 中文名与中文释义的映射文件（YAML）
# 键为相对仓库根目录的文件路径；值为对象，包含：
#   cn:   中文名（短标题）
#   desc: 中文释义（模板用途说明，越详细越好）
#
# 例子：
# backend/templates/upload_orders.html:
#   cn: 订单导入
#   desc: 用于上传 Excel/CSV 并按列映射订单号与运单号的三步式向导页面（步骤 1/3 选择文件）。
#
# 提示：可在编辑器左侧“信息”按钮在线修改，无需手工编辑本文件。

editor/templates/editor.html:
  cn: 模版编辑器主页
  desc: 模版管理主界面；左为模版列表（可搜索、编辑、导出），右为代码编辑与点击后才渲染的预览区域；工具栏支持一键打包与导出 ZIP。

editor/templates/login.html:
  cn: 登录页
  desc: 模版编辑器独立登录页面（与后台管理分离）；输入账号密码后进入编辑界面。

editor/static/editor.css:
  cn: 编辑器样式
  desc: 控制编辑器整体视觉（深色、圆角、工具栏、列表与编辑区网格布局等）；可在此调整尺寸与间距。
