permissions:
  - key: logistics.view
    title: 物流-查看
    desc: L1 物流模块访问权限
  - key: logistics.custom.view
    title: 自定义物流-查看
    desc: L3 页面可见与数据查看
  - key: logistics.custom.manage
    title: 自定义物流-管理
    desc: 新增/编辑/停用/删除
