module:
  key: system_upgrade
  title: 系统更新
  version: 0.1.0
  build_at: "2025-09-27 23:12:57 UTC"
  backend:
    routers:
      - modules/system_settings/system_upgrade/backend/routers/system_upgrade.py
  frontend:
    templates:
      - modules/system_settings/system_upgrade/frontend/templates/system_upgrade.html
      - modules/system_settings/system_upgrade/frontend/templates/modals/settings.html
      - modules/system_settings/system_upgrade/frontend/templates/modals/log.html
    static:
      - modules/system_settings/system_upgrade/frontend/static/system_upgrade.css
      - modules/system_settings/system_upgrade/frontend/static/system_upgrade.js
  permissions:
    - settings.view
    - settings.system.view
    - settings.system.upgrade.view
    - settings.system.upgrade.manage
