# modules/system_settings/system_upgrade/config/permissions.register.yaml
permissions:
  - key: settings.view
    title: 设置-查看
    desc: L1 设置模块访问权限
  - key: settings.system.view
    title: 系统设置-查看
    desc: L2 系统设置访问权限
  - key: settings.system.upgrade.view
    title: 系统更新-查看
    desc: L3 页面可见与数据查看
  - key: settings.system.upgrade.manage
    title: 系统更新-管理
    desc: 执行更新/回滚/删除
